# Generated by Django 4.2 on 2023-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type_of_exercise',
            field=models.CharField(choices=[('Sit-ups', 'Sit-ups'), ('Jumping-jacks', 'Jumping-jacks')], max_length=15),
        ),
    ]
