# Generated by Django 4.2 on 2023-04-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0003_alter_exercise_type_of_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='data_of_exercise',
            new_name='date_of_exercise',
        ),
    ]
