# Generated by Django 4.2 on 2023-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0004_rename_data_of_exercise_exercise_date_of_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_of_exercise',
            field=models.DateTimeField(null=True),
        ),
    ]
