# Generated by Django 4.2 on 2023-04-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0005_alter_exercise_date_of_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('seconds_elapsed', models.FloatField()),
                ('z', models.FloatField()),
                ('y', models.FloatField()),
                ('x', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_data', to='rehab.exercise')),
            ],
        ),
    ]
